[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  VITE_SUPABASE_URL = "Your Supabase project URL"
  VITE_SUPABASE_ANON_KEY = "Your Supabase anonymous key"
```